# Generated by Django 2.2.13 on 2020-06-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200622_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='dfgtrgws',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='fdgfgv',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='xfwdrg',
        ),
    ]
