# Generated by Django 2.2.13 on 2020-06-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200622_0639"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="assd",),
        migrations.RemoveField(model_name="homepage", name="dfa",),
        migrations.RemoveField(model_name="homepage", name="sd",),
    ]
