# Generated by Django 2.2.13 on 2020-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200622_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jhljkhkljh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgkjghgk', models.BigIntegerField()),
            ],
        ),
    ]
